version: "3.1"
services:
  pushservice:
    image: txservice
    build:
      context: ./txs
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - ./ggc.json:/home/ggc.json
    working_dir: /home
    entrypoint: [./run.sh]
    environment:
      MODE: "push"
    env_file:
      - service.env
    depends_on:
      - mongo
  broadcast:
    image: txservice
    working_dir: /home
    entrypoint: [./run.sh]
    volumes:
      - ./ggc.json:/home/ggc.json
    environment:
      MODE: "broadcast"
    env_file:
      - service.env
    depends_on:
      - pushservice
  status:
    image: txservice
    working_dir: /home
    entrypoint: [./run.sh]
    volumes:
      - ./ggc.json:/home/ggc.json
    environment:
      MODE: "status"
    env_file:
      - service.env
    depends_on:
      - pushservice
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data/mongodb:/data/db
      - ./data/mongodb_config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9003:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
