version: '3.1'
services:
  mongov2:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-expressv2:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongov2
volumes:
  mongodb:
  mongodb_config: