version: "3.1"
services:
  chainsyncv3:
    image: alpine
    volumes:
      - .:/home
      - ./chain:/chain
    entrypoint: [/home/run.sh]
    environment:
      INDEXERID: 10
      MODE: "chainsync"
      PORT: 9001
      INCOGNITO_NETWORK_KEY: "local"
      INCOGNITO_CONFIG_MODE_KEY: "file"
      INCOGNITO_CONFIG_DIR_KEY: "/home/config"
    depends_on:
      - mongov3

  queryv3:
    image: alpine
    volumes:
      - .:/home
    entrypoint: [/home/run.sh]
    environment:
      INDEXERID: 0
      MODE: "query"
      PORT: 9008
    depends_on:
      - chainsyncv3

  indexer0v3:
    image: alpine
    volumes:
      - .:/home
    entrypoint: [/home/run.sh]
    environment:
      INDEXERID: 0
      MODE: "indexer"
      PORT: 9009
    depends_on:
      - chainsyncv3
      - mongov3

  worker1:
    image: alpine
    volumes:
      - .:/home
    entrypoint: [/home/run.sh]
    environment:
      INDEXERID: 1
      MODE: "indexworker"
      PORT: 9001
    depends_on:
      - indexer0v3

  worker2:
    image: alpine
    volumes:
      - .:/home
    entrypoint: [/home/run.sh]
    environment:
      INDEXERID: 2
      MODE: "indexworker"
      PORT: 9001
    depends_on:
      - indexer0v3

  worker3:
    image: alpine
    volumes:
      - .:/home
    entrypoint: [/home/run.sh]
    environment:
      INDEXERID: 3
      MODE: "indexworker"
      PORT: 9001
    depends_on:
      - indexer0v3

  worker4:
    image: alpine
    volumes:
      - .:/home
    entrypoint: [/home/run.sh]
    environment:
      INDEXERID: 4
      MODE: "indexworker"
      PORT: 9001
    depends_on:
      - indexer0v3

  nginx-server:
    image: nginx-load-balancer
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 9080:80
    restart: unless-stopped
    depends_on:
      - queryv3
      - indexer0v3

  watcher:
    image: alpine
    volumes:
      - .:/home
    entrypoint: [/home/servicewatcher]
    environment:
      CSVSYNCKER: "http://chainsyncv3:9001"
      FULLNODE: "http://51.161.119.66:9334"
    depends_on:
      - chainsyncv3

  mongov3:
    image: mongo
    restart: always
    # ports:
    #   - 27019:27017
    volumes:
      - ./mongodb:/data/db
      - ./mongodb_config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-expressv3:
    image: mongo-express
    restart: always
    ports:
      - 8085:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongov3
# volumes:
#   mongodb:
#   mongodb_config:
