name: Go

on:
  push:
    branches: [ main, production ]
  pull_request:
    branches: [ main, production ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    
    - name: Download go mod
      run: go mod download
      
    - name: Build
      run: go build -v ./...


